#!/usr/bin/env node
/**
 * check:anchors - every in-page link on this site lands somewhere, and #access can never stop existing.
 *
 *   node scripts/check-anchors.mjs      (npm run check:anchors, and prebuild)
 *   Exit 0 = every literal anchor resolves; 1 = at least one does not; 2 = could not measure.
 *
 * ## THE ONE THAT CANNOT BE FIXED LATER
 *
 * `lib/seatrade/config.ts` builds `PILOT_URL` as `${SITE_URL}/#access`, and that link is inside
 * Seatrade Cruise Med 2026 mail that has ALREADY BEEN DELIVERED to real inboxes. Those messages
 * cannot be edited. So `id="access"` is not a naming preference on this site, it is a permanent
 * obligation to people who were handed the link at a trade show, and a refactor that renames the
 * section breaks it silently: the page still loads, it just does not scroll, and nobody who did it
 * ever sees the failure. That is why this is a gate and not a comment in the section it protects.
 *
 * ## AND THE GENERAL FORM, BECAUSE THE NEXT BROKEN ANCHOR WILL NOT BE #access
 *
 * A gate that checked only `#access` would have passed the day `#how` broke. `ValueSection` owned
 * that id, it was deleted on 17.09.2026, and two rows kept pointing at it: `Footer.tsx` and
 * `PageNav.tsx`. So the check is an invariant over the whole set - every literal same-page anchor
 * has a literal `id` to land on - and `#access` is a named floor on top of it.
 *
 * ## SCOPE IS DECLARED, BECAUSE A ZERO IS ONLY EVER A SCOPED ZERO
 *
 * LITERAL anchors and LITERAL ids only. `href={`#hero-stage-${i + 1}`}` is built at runtime and so
 * is the `id` it targets; both are invisible here, which is consistent rather than lucky - the pair
 * is generated by one loop in one file. Interpolated anchors are counted and printed so the
 * coverage is visible rather than assumed.
 *
 * ## THE INSTRUMENT IS CALIBRATED BEFORE ANY ZERO FROM IT IS BELIEVED
 *
 * A known-positive anchor that really is linked must be FOUND linked, a known-positive id must be
 * FOUND declared, and a fabricated anchor must be REPORTED missing. A regex that matches nothing
 * reports "every anchor resolves" and looks exactly like a healthy site.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** Same scope as scripts/lint-dashes.mjs: the code that renders portlink.app's own pages. */
const INCLUDE_DIRS = ['app', 'components', 'hooks']
const EXCLUDE_PREFIXES = ['app/_ds/', 'app/seatrade/', 'components/seatrade/']
const EXTS = ['.ts', '.tsx']

/**
 * Anchors that must exist whatever else changes, with the reason they outlive this repo.
 *
 * `access` is here rather than derived, because deriving it from `lib/seatrade/config.ts` would
 * make the obligation disappear the day that file changes - and the mail carrying the link would
 * still be in people's inboxes. An obligation to somebody outside the repository cannot be
 * conditional on anything inside it.
 */
const REQUIRED = [
  { anchor: 'access', why: 'lib/seatrade/config.ts builds PILOT_URL as ${SITE_URL}/#access, and that link is in Seatrade mail already delivered. It cannot be edited.' },
  { anchor: 'pilot', why: 'the homepage nav, the footer and PageNav all carry a Pilot row pointing at it.' },
  { anchor: 'main', why: 'the skip link in app/layout.tsx targets it, and it is the first focusable node on every page.' },
]

const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/')

function fail(msg, code = 1) {
  console.error(`\ncheck:anchors FAILED\n  ${msg}`)
  process.exit(code)
}

function listFiles(dir) {
  const out = []
  const full = path.join(ROOT, dir)
  if (!fs.existsSync(full)) return out
  const walk = (d) => {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const f = path.join(d, entry.name)
      if (entry.isDirectory()) walk(f)
      else if (entry.isFile() && EXTS.some((e) => entry.name.endsWith(e))) out.push(f)
    }
  }
  walk(full)
  return out.filter((f) => !EXCLUDE_PREFIXES.some((p) => rel(f).startsWith(p)))
}

const files = INCLUDE_DIRS.flatMap(listFiles)
if (files.length === 0) fail('no source files in scope. The scanner is reading the wrong tree.', 2)

/* `href="#x"` and `href="/#x"`, in a JSX attribute or a plain object literal, single or double
   quoted. A bare `href="#"` has no anchor and is skipped, not reported. */
const LINK_RE = /href\s*[:=]\s*['"]\/?#([A-Za-z][\w-]*)['"]/g
const ID_RE = /\bid\s*[:=]\s*['"]([A-Za-z][\w-]*)['"]/g
/** An anchor assembled at runtime. Counted so the scope is printed, never silently omitted. */
const INTERPOLATED_RE = /href\s*[:=]\s*\{?`\/?#/g

const linked = new Map()
const ids = new Set()
let interpolated = 0

for (const file of files) {
  const src = fs.readFileSync(file, 'utf8')
  for (const m of src.matchAll(LINK_RE)) {
    if (!linked.has(m[1])) linked.set(m[1], new Set())
    linked.get(m[1]).add(rel(file))
  }
  for (const m of src.matchAll(ID_RE)) ids.add(m[1])
  interpolated += [...src.matchAll(INTERPOLATED_RE)].length
}

// ── Calibration ─────────────────────────────────────────────────────────────
if (!linked.has('access')) fail('the link scanner found no `#access` anywhere, and the nav, the footer and the hero all carry it. The pattern is broken, so a clean result here means nothing.', 2)
if (!ids.has('access')) fail('the id scanner found no `id="access"`, which AccessSection declares literally. The pattern is broken.', 2)
if (ids.has('a-fabricated-anchor-that-cannot-exist')) fail('the id scanner matched a string that is not in the source. It is not measuring the files.', 2)
{
  /* Known negative: a fabricated anchor must come out unresolved, or the comparison below cannot
     report anything at all. Run on a copy of the real sets, so it cannot affect the verdict. */
  const probe = new Set(ids)
  if (probe.has('fabricated-probe-anchor')) fail('impossible: the probe anchor exists in the source.', 2)
  const unresolvedProbe = ['fabricated-probe-anchor'].filter((a) => !probe.has(a))
  if (unresolvedProbe.length !== 1) fail('the comparison cannot report a missing anchor. Every clean result from it would be a false clean.', 2)
}

// ── Verdict ─────────────────────────────────────────────────────────────────
const broken = [...linked.entries()]
  .filter(([anchor]) => !ids.has(anchor))
  .map(([anchor, from]) => `#${anchor} is linked from ${[...from].sort().join(', ')} and no file declares id="${anchor}".`)

const missingRequired = REQUIRED
  .filter((r) => !ids.has(r.anchor))
  .map((r) => `id="${r.anchor}" is required and absent. ${r.why}`)

console.log(`check:anchors: ${files.length} file(s) in scope, ${linked.size} literal anchor(s) linked, ${ids.size} literal id(s) declared, ${interpolated} interpolated anchor(s) out of scope.`)
console.log(`  calibration: #access found linked and declared; a fabricated anchor was correctly reported unresolved.`)
for (const r of REQUIRED) console.log(`  required  id="${r.anchor}"  ${ids.has(r.anchor) ? 'present' : 'MISSING'}`)
console.log(`  excluded: ${EXCLUDE_PREFIXES.join(' ')}`)

if (broken.length || missingRequired.length) fail([...missingRequired, ...broken].join('\n  '))

console.log('\ncheck:anchors clean. Every literal in-page link in scope lands on a declared id.')
