#!/usr/bin/env node
/**
 * check:anchors - every in-page link on this site lands somewhere, and #access can never stop existing.
 *
 *   node scripts/check-anchors.mjs      (npm run check:anchors, and prebuild)
 *   Exit 0 = every literal anchor resolves; 1 = at least one does not; 2 = could not measure.
 *
 * ## THE ONE THAT CANNOT BE FIXED LATER
 *
 * `lib/seatrade/config.ts` builds `PILOT_URL` as `${SITE_URL}/#access`, and that link is inside
 * Seatrade Cruise Med 2026 mail that has ALREADY BEEN DELIVERED to real inboxes. Those messages
 * cannot be edited. So `id="access"` is not a naming preference on this site, it is a permanent
 * obligation to people who were handed the link at a trade show, and a refactor that renames the
 * section breaks it silently: the page still loads, it just does not scroll, and nobody who did it
 * ever sees the failure. That is why this is a gate and not a comment in the section it protects.
 *
 * ## AND THE GENERAL FORM, BECAUSE THE NEXT BROKEN ANCHOR WILL NOT BE #access
 *
 * A gate that checked only `#access` would have passed the day `#how` broke. `ValueSection` owned
 * that id, it was deleted on 17.09.2026, and two rows kept pointing at it: `Footer.tsx` and
 * `PageNav.tsx`. So the check is an invariant over the whole set - every literal same-page anchor
 * has a literal `id` to land on - and `#access` is a named floor on top of it.
 *
 * ## SCOPE IS DECLARED, BECAUSE A ZERO IS ONLY EVER A SCOPED ZERO
 *
 * LITERAL anchors and LITERAL ids only. `href={`#hero-stage-${i + 1}`}` is built at runtime and so
 * is the `id` it targets; both are invisible here, which is consistent rather than lucky - the pair
 * is generated by one loop in one file. Interpolated anchors are counted and printed so the
 * coverage is visible rather than assumed.
 *
 * ## THE INSTRUMENT IS CALIBRATED BEFORE ANY ZERO FROM IT IS BELIEVED
 *
 * A known-positive anchor that really is linked must be FOUND linked, a known-positive id must be
 * FOUND declared, and a fabricated anchor must be REPORTED missing. A regex that matches nothing
 * reports "every anchor resolves" and looks exactly like a healthy site.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')

/** Same scope as scripts/lint-dashes.mjs: the code that renders portlink.app's own pages. */
const INCLUDE_DIRS = ['app', 'components', 'hooks']
const EXCLUDE_PREFIXES = ['app/_ds/', 'app/seatrade/', 'components/seatrade/']
const EXTS = ['.ts', '.tsx']

/**
 * Anchors that must exist whatever else changes, with the reason they outlive this repo.
 *
 * `access` is here rather than derived, because deriving it from `lib/seatrade/config.ts` would
 * make the obligation disappear the day that file changes - and the mail carrying the link would
 * still be in people's inboxes. An obligation to somebody outside the repository cannot be
 * conditional on anything inside it.
 */
const REQUIRED = [
  { anchor: 'access', why: 'lib/seatrade/config.ts builds PILOT_URL as ${SITE_URL}/#access, and that link is in Seatrade mail already delivered. It cannot be edited.' },
  { anchor: 'pilot', why: 'the homepage nav, the footer and PageNav all carry a Pilot row pointing at it.' },
  { anchor: 'main', why: 'the skip link in app/layout.tsx targets it, and it is the first focusable node on every page.' },
]

const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/')

function fail(msg, code = 1) {
  console.error(`\ncheck:anchors FAILED\n  ${msg}`)
  process.exit(code)
}

function listFiles(dir) {
  const out = []
  const full = path.join(ROOT, dir)
  if (!fs.existsSync(full)) return out
  const walk = (d) => {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const f = path.join(d, entry.name)
      if (entry.isDirectory()) walk(f)
      else if (entry.isFile() && EXTS.some((e) => entry.name.endsWith(e))) out.push(f)
    }
  }
  walk(full)
  return out.filter((f) => !EXCLUDE_PREFIXES.some((p) => rel(f).startsWith(p)))
}

const files = INCLUDE_DIRS.flatMap(listFiles)
if (files.length === 0) fail('no source files in scope. The scanner is reading the wrong tree.', 2)

/* `href="#x"` and `href="/#x"`, in a JSX attribute or a plain object literal, single or double
   quoted. A bare `href="#"` has no anchor and is skipped, not reported. */
const LINK_RE = /href\s*[:=]\s*['"]\/?#([A-Za-z][\w-]*)['"]/g
const ID_RE = /\bid\s*[:=]\s*['"]([A-Za-z][\w-]*)['"]/g
/** An anchor assembled at runtime. Counted so the scope is printed, never silently omitted. */
const INTERPOLATED_RE = /href\s*[:=]\s*\{?`\/?#/g

const linked = new Map()
const ids = new Set()
let interpolated = 0

for (const file of files) {
  const src = fs.readFileSync(file, 'utf8')
  for (const m of src.matchAll(LINK_RE)) {
    if (!linked.has(m[1])) linked.set(m[1], new Set())
    linked.get(m[1]).add(rel(file))
  }
  for (const m of src.matchAll(ID_RE)) ids.add(m[1])
  interpolated += [...src.matchAll(INTERPOLATED_RE)].length
}

// ── Calibration ─────────────────────────────────────────────────────────────
/*
 * ⛔ THE PATTERNS ARE CALIBRATED ON FIXTURES, NOT ON THE REPOSITORY, AND THAT DISTINCTION IS THE
 * WHOLE POINT. The first version of this file calibrated by asserting that `id="access"` was found
 * in the source. Renaming that id therefore produced "the pattern is broken" (exit 2) instead of
 * "the required anchor is absent" (exit 1) - the gate blamed itself for the exact defect it exists
 * to report, and a gate that says something untrue about a real break is one somebody switches off.
 * Measured on this branch by renaming the id and reading the message.
 *
 * So: the patterns are proven against strings held here, and the repository is then judged only by
 * REQUIRED and by the link-to-id comparison. Nothing about the verdict depends on any particular
 * id still existing.
 */
{
  const FIXTURE = [
    'const a = { label: "Access", href: "#access-fixture" }',
    '<a href="/#pilot-fixture">Pilot</a>',
    '<a href="#">logo, no anchor</a>',
    '<section id="access-fixture">',
    '<div idx="not-an-id">',
  ].join('\n')

  const fLinks = [...FIXTURE.matchAll(LINK_RE)].map((m) => m[1]).sort()
  const fIds = [...FIXTURE.matchAll(ID_RE)].map((m) => m[1]).sort()

  if (fLinks.join(',') !== 'access-fixture,pilot-fixture') {
    fail(`the link pattern extracted [${fLinks}] from a fixture holding exactly #access-fixture and /#pilot-fixture. It is broken, so every clean result from it would be a false clean.`, 2)
  }
  if (fIds.join(',') !== 'access-fixture') {
    fail(`the id pattern extracted [${fIds}] from a fixture holding exactly one id. It is broken.`, 2)
  }
  /* The comparison itself must be able to report a miss, or a clean run means nothing. */
  const unresolved = fLinks.filter((a) => !fIds.includes(a))
  if (unresolved.join(',') !== 'pilot-fixture') {
    fail('the link-to-id comparison did not report the fixture anchor that has no id. It cannot report a real one either.', 2)
  }
}

/* Repository sanity, which is a different question from pattern sanity: zero files, zero ids or
   zero links means this is pointed at the wrong tree, not that the site is clean. */
if (ids.size === 0) fail('no literal id declared anywhere in scope. The scanner is reading the wrong tree.', 2)
if (linked.size === 0) fail('no literal in-page anchor linked anywhere in scope. The scanner is reading the wrong tree.', 2)

// ── Verdict ─────────────────────────────────────────────────────────────────
const broken = [...linked.entries()]
  .filter(([anchor]) => !ids.has(anchor))
  .map(([anchor, from]) => `#${anchor} is linked from ${[...from].sort().join(', ')} and no file declares id="${anchor}".`)

const missingRequired = REQUIRED
  .filter((r) => !ids.has(r.anchor))
  .map((r) => `id="${r.anchor}" is required and absent. ${r.why}`)

console.log(`check:anchors: ${files.length} file(s) in scope, ${linked.size} literal anchor(s) linked, ${ids.size} literal id(s) declared, ${interpolated} interpolated anchor(s) out of scope.`)
console.log(`  calibration: both patterns verified against fixtures, and the comparison reported the fixture anchor that had no id.`)
for (const r of REQUIRED) console.log(`  required  id="${r.anchor}"  ${ids.has(r.anchor) ? 'present' : 'MISSING'}`)
console.log(`  excluded: ${EXCLUDE_PREFIXES.join(' ')}`)

if (broken.length || missingRequired.length) fail([...missingRequired, ...broken].join('\n  '))

console.log('\ncheck:anchors clean. Every literal in-page link in scope lands on a declared id.')
